### ISSUE TITLE
Replace nodejs Buffer with Uint8array

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#10]
Buffer is nodejs construct polyfilled in browser. All major browsers now support Uint8array, we should use it instead as well.

**Comment by vojtechsimetka** [comment]
I just checked and except for tests I could not find any `Buffer` anymore. Hence closing

**Comment by agazso** [comment]
Unfortunately `prepareData` from `src/utils/data.ts` is using Buffer in the case when `string` is passed in as data. It is trivial to fix though (using `TextEncoder`).
