### ISSUE TITLE
Export some of the utility functions

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#103]
## Rationale
It is likely some of the common functions like `hexToBytes` could be useful for devs who use our library.

## Task
Export new namespace `utils` with some of the most sensible functions. E.g `hexToBytes`, `bytesToHex` or `stripPrefix`

**Comment by nugaon** [comment]
I suggest using CamelCase with uppercase starting letter on namespaces (same as in case of objects, which only contain other properties).

See #46
