### ISSUE TITLE
Create CI running against latest Bee on the Release PR

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#104]
## Rationale
The master branch on the `bee` repository includes changes that will likely end up in the next release. We should periodically check if our next release is compatible with the newest changes.

**Comment by AuHau** [comment]
Yeah, I would like to have this as well. This will need to trigger Bee Factory build automatically based on Bee release for which we could use https://github.com/peter-evans/repository-dispatch action. Then we would have a non-required action that would test again latest.

**Comment by AuHau** [comment]
This was implemented as part of Bee factory image update upon Bee release. Maybe a bit different form, but I would say still achieving the same goal, so closing this.
