### ISSUE TITLE
URL default values and debug URL handling

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#127]
* should be refactored the debug url handling (introduce `BEE_DEBUG_URL` or something similar),
* change default fallback values of these URL variables to a more straightforward one (e.g. `http://localhost:1633` on `BEE_API_URL` and `http://localhost:11633` on `BEE_PEER_API_URL`

_copied from PR #124_

**Comment by AuHau** [comment]
I believe this is done.
