### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#144]
Currently, the root of the repo has many items and contains things that are not directly needed for the functionality of the project, such as `.vscode` folder.

They are mostly related to the VSCode configuration/working which IMO should not be part of the repo as IDE is a personal choice of contributor's workflow and different people have different work styles with different IDEs. Having configuration for all of them is not feasible.

@nugaon pointed out that he would like to support users of VSCode with the prepared configurations for our repos, so maybe we should find some other way how to achieve that.

Generally, IMO simplicity and cleanness help for better maintainability, readability, and easy orientation for newcomers. Having a clean root folder of the repo is part of that.

**Comment by nugaon** [comment]
> @nugaon pointed out that he would like to support users of VSCode with the prepared configurations for our repos, so maybe we should find some other way how to achieve that.

As I proposed in the discussion regards to this, creating a `contribution` folder would be nice to place these  _functional_ configurations for dev environment. Thereby the before mentioned `.vscode` folder would be listed in `.gitignore`, but would have the opportunity to copy/paste predefined useful configurations related to development like `.vscode` to its place by a NPM command.

Would be nice if the PR which resolves this issue would put other neccessary information about contribution into this proposed folder.
