### ISSUE TITLE
Rename Owner to OwnerAddress

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#152]
Honestly, I think the type and the property should be named `OwnerAddress` as `Owner` IMO does not really explain what it actually contains and as it is only an alias to `EthAddress`. Eq. it could be some object with metadata etc...

_Originally posted by @AuHau in https://github.com/ethersphere/bee-js/pull/136#discussion_r582863582_

**Comment by AuHau** [comment]
In the end I propose to actually drop the concept of `Owner` type as it is `EthAddress` and making "alias" like this does not really make sense IMO.
