### ISSUE TITLE
npm install & runtime errors on Centos node 9.3.0

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee-js#161]
I'm working on a bee node monitor using node.js and am trying to migrate it to use bee-js.  I worked with a friend to try to install and run it on a machine other than my own.  After going through the following installations, we got up to @ethersphere/bee-js.

nodejs & npm packages
npm installs for axios and blessed

npm install @ethersphere/bee-js --save

The final command gave errors which, unfortunately I only have as a screen capture:

https://cdn.discordapp.com/attachments/815040773706743849/815052005557928026/unknown.png
or
https://gateway.ethswarm.org/files/717e84887da690fced6cdd7f8730c642429e61309e07a30cee66cb6f027998a9

Being a JavaScript and node.js rookie, I had to look up what "You must install peer dependencies yourself" meant.  I did NOT get this error on my Windows-based development machine (14.16.0), nor another Ubuntu machine (15.10.0), but this happened on Centos with node 9.3.0.

One link said "they're only warnings, ignore them and run anyway", so we did try to run my monitor, but received the following "Unexpected reserved word" error:

https://cdn.discordapp.com/attachments/815040773706743849/815054947271049226/unknown.png
or
https://gateway.ethswarm.org/files/0f3f8e9a80aade560f56bdeecadecdd4dd3869e8c6eccc22b7068e216fde52cc

Ok, so maybe we DO need those "peer dependencies", so we installed them as:

npm install --save-dev bufferutil@^4.0.1
npm install --save-dev utf-8-validate@^5.0.2

And then tried my monitor again, but we still get, and continue to get, the "Unexpected reserved word".

I no longer have direct access to the machine on which this is occurring, but after having removed the bee-js dependencies from my monitor tool, it runs fine, so the issue is strictly when I attempt to invoke bee-js, apparently right from the require statement if I read the stack dump correctly.

const { BeeDebug } = require("@ethersphere/bee-js")

is the line of my script that brings in BeeDebug (/bee-soft/monBee.js line 12).

**Comment by vojtechsimetka** [comment]
Hi, from your description it looks like your are using unsupported version of nodejs. We only support current nodejs versions which are 10 (which we will drop in 2 months), 12, 14 and 15. See the official nodejs release page https://nodejs.org/en/about/releases/

Please update your nodejs environment and let me know if that fixed it.

**Comment by ldeffenb** [comment]
Then the Centos folks need to get their packages updated because I believe node 9.3.0 is what came automatically when nodejs was installed.  If I have a chance, I'll get with the person to see if he can get a newer version of nodejs.
