### ISSUE TITLE
Check for trailing `/` in `url` in constructor

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#165]
This might lead to weird errors for example in the browser where the browser might do [CORS Preflight check](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests) (eq. `OPTIONS` request to Bee) to URL `http://localhost:1633//bytes` to which Bee replies with redirect response which browser rejects as an invalid reply.

**Comment by agazso** [comment]
It would be good to use the [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL) also for validating if the passed in url is a correct one.

Then the `.origin` property can be used for storing the actual url without trailing `/`.

**Comment by AuHau** [comment]
I don't think using `.origin` is a good idea. What if the Bee node sits behind reverse proxy under some path? Then URL like `https://some-domain.com:1234/bee-node` would not work.

**Comment by agazso** [comment]
I don't think Bee was ever anticipated to work well in this situation as well. For example if you make a request to the `/bzz/<hash>` endpoint it will respond a HTTP 308 (Permanent redirect) response to `/bzz/<hash>` which then would fail.

**Comment by AuHau** [comment]
Hmm, while this might be the current non-optimal behavior, I would avoid "deepening" the problem even further. We are using URL to pinpoint the Bee node, so we should expect that people will use the full feather set it supports and which is intuitive to them. If we really want to support only this basic setup, then I would drop support for URLs in the constructor and simply ask for `hostname` and `port` instead.
