### ISSUE TITLE
Improve custom `Signer` types

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#166]
When a custom `Signer` is passed to `makeFeedWriter` or `makeSOCWriter` it is validated in a very simple manner to follow the `Signer` interface. This should be improved to validate for example that `address` is indeed `EthAddress` (eq. `Bytes<20>`) type and not hex string that might be passed otherwise.

Currently, the calls fail with error `400: bad owner` which does not says much.

**Comment by agazso** [comment]
You may want to use `verifyBytes(20, address)` for that

**Comment by AuHau** [comment]
Yeah, or I might even go so far as allow `HexAddress` as well in `address`.

**Comment by AuHau** [comment]
Upon working on the Ethereum wallet signing, I bumped into a rather irritating problem where the interface uses `Bytes` while the common type in Ethereum is `HexString` which leads to a lot of conversions from/to bytes to/from hex strings. I expect that the biggest group of custom Signers will be using HexStrings, so I would propose to allow correctly validated `HexString` as input/output of `Signer` as well.

See: https://github.com/ethersphere/bee-js/pull/168/files#diff-9576d5f38c5e309082bc2573cef0e58eb5bfd6e1a44239aba036ee64686b12e2R36

**Comment by AuHau** [comment]
This is resolved with #223
