### ISSUE TITLE
Flakey tests

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#178]
We have tests that are sometimes flakey, which is not surprising because most of our tests are actually integration tests.
The worst offenders are the PSS tests and feed lookup/update (see an [open issue about this](https://github.com/ethersphere/bee/issues/1248#issuecomment-786588911))

Currently our solution is to increase the test timeout so that they most likely finish.

**Comment by AuHau** [comment]
In my experience, this has vastly improved to a point that I don't think there is no action here, so closing.
