### ISSUE TITLE
getChequeubookBalance is spelled worng (sic)

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee-js#183]
Ok, I tried to make the required change to the 3 necessary files, but apparently I've got more to learn about how to format a proper commit message.  So instead of actually contributing, I'll just open an issue.

getChequeubookBalance is spelled with an extra u, consistently, but wrong.  It should be getChequebookBalance to match the other chequebook API wrappers.

**Comment by vojtechsimetka** [comment]
Hey, yes sorry for that. We are using conventional commits which helps us to automatically generate changelog - https://www.conventionalcommits.org/en/v1.0.0/

I've taken your code and just fixed the commit name :) (see #184 ) . Next time feel free to ask, I'll happily guide you through the process

**Comment by AuHau** [comment]
Yeah, we should add the information about Conventional Commits to the README...
