### ISSUE TITLE
The bee runner automatically adds issue and pull-request labels

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#185]
We now have quite nice labelling system which I would like to use exclusively. However, it is annoying to manually fix the labels after crating PR/issue as the @bee-runner automatically adds `pull-request` or `issue` label. @AuHau could you try and resolve this?

**Comment by AuHau** [comment]
Bee Runner is getting configuration options: https://github.com/ethersphere/bee-runner/pull/4
