### ISSUE TITLE
Return data type for download functions

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#191]
Currently we are returning `Uint8Array` types from the download functions (and pssReceive) because it is suitable type for representing potentially binary data. However it is not easy to use and most people are not familiar with it. For example to convert it to string you have to use the `TextDecoder` class which is also something most developers are not familiar with (for illustration see #174).

Maybe it would be better to define a new type that could hold a `Uint8Array` for the binary data representation but would also provide conversion functions to text and json, similarly to the `Response` API used by `fetch`. For example:

```typescript
interface Data {
   readonly bytes: Uint8Array
   text: () => string
   json: () => Record<string, any>
}
```

Then we could return this interface from our functions everywhere with the help of an implementation that takes a `Uint8Array` and creates this type from it.

**Comment by agazso** [comment]
The interface could also include a `hex: () => HexString` function that returns the data as a hex string.

**Comment by AuHau** [comment]
Yup! I like it and I think it is really necessary.

**Comment by AuHau** [comment]
Hmm should the `hex()` function return prefixed or non-prefixed hex? 😅

**Comment by agazso** [comment]
I would say non-prefixed. Prefixing with `'0x'` seems easier than `.slice(2)` to me. Alternatively we can provide another function that returns prefixed hex.

**Comment by AuHau** [comment]
I have come up with two options for how to approach this. One will introduce breaking change and one not.

1. Wrap the bytes as @agazso proposed. Eq. returning instead of `Uint8Array` an object like he proposed. (breaking change)
2. Extend the `Uint8Array` object with the helpers functions like this:

```ts
export function wrapBytesWithHelpers(data: Uint8Array): Data {
  return Object.assign(data, {
    text: () => new TextDecoder('utf-8').decode(data),
    json: () => JSON.parse(new TextDecoder().decode(data)),
    hex: () => bytesToHex(data),
  })
}
```

What do you think?

**Comment by agazso** [comment]
I was thinking of this too and this is also good. And considering that it does not cause a breaking change I would go with it.

**Comment by vojtechsimetka** [comment]
> Hmm should the `hex()` function return prefixed or non-prefixed hex? 😅

I am all for non-prefixed, but you could add optional flag 
```ts
hex: (prefixed = false) => `${prefixed ? '0x' : ''}${bytesToHex(data)}`
```

> I have come up with two options for how to approach this. 

Even though it is a breaking change, I would personally prefer option 1. But no strong prefference

**Comment by agazso** [comment]
> > Hmm should the `hex()` function return prefixed or non-prefixed hex? 😅
> 
> I am all for non-prefixed, but you could add optional flag
> 
> ```ts
> hex: (prefixed = false) => `${prefixed ? '0x' : ''}${bytesToHex(data)}`
> ```

That's possible to do, however then the return type will be ambiguous (e.g. `HexString | PrefixedHexString`), which is not a problem for Javascript users but it may be a bit more difficult to work with for Typescript users.

**Comment by AuHau** [comment]
Ok, the only thing I am not sure if we won't introduce a memory leak with this approach of "wrapping" (it is applicable for both approaches), because they atm. rely on closure and I am not sure if the closure will be properly GCed. What do you think?

**Comment by agazso** [comment]
It's only a problem with GC when you have circular references. This case is equivalent having a class with the data passed in the constructor. Actually it would be also possible to do that, but I usually prefer a more functional approach.
