### ISSUE TITLE
Manifest support with mantaray

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#196]
Currently Bee only has support for uploading collections but not adding files to it or deleting files from them. It would be possible to add support for collections if we implemented [mantaray](https://github.com/ethersphere/manifest) support in bee-js. Mantaray is a binary serialization format used in the implementation of collections and (file) manifests.

Then we could download the manifest, manipulate it directly and then reupload it, effectively implementing what add or delete would do on the Bee Go client.

See also #172.

**Comment by AuHau** [comment]
IMO this is solved with the [`manifest-js`](https://github.com/ethersphere/manifest-js/) library, so closing this.
