### ISSUE TITLE
Chequebook breaking change

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#210]
There is an upcoming breaking change in the cashout status. For more context see:

https://github.com/ethersphere/bee/pull/1402

**Comment by ralph-pichler** [comment]
fyi the PR and api change is already final. I am just waiting with merging until after the next minor release.

**Comment by vojtechsimetka** [comment]
Thanks for the heads up! Will do this today.

**Comment by ralph-pichler** [comment]
PR was merged

**Comment by AuHau** [comment]
This was included in our release version, so closing this.
