### ISSUE TITLE
Expanding unit tests - mocking / stubbing / patching

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#227]
With @agazso we discussed that there is a need for extended unit testing that would not really on the external Bee node but would be able to cover some test cases without that. 

I suggested to start using library like `spy` or [@fluffy-spoon/substitute](https://www.npmjs.com/package/@fluffy-spoon/substitute). This could be introduced when working on the #197 issue.

**Comment by agazso** [comment]
Jest has built-in support for mock/spies: https://jestjs.io/docs/mock-function-api

It would be good to evaluate that to see if it works for our use-case.
