### ISSUE TITLE
Compile distinct browser source code 

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#24]
There should be a possibility to substitute arbitrary source files with the browser-side implementation of its functions.

Currently neither Webpack nor Jest can handle distinction among of Node or Browser functionalities at build.

The proposal is stick with NodeJS implementation by default and where is necessary create a [X].browser.ts file which fully implements functions of [X].ts file.

**Comment by agazso** [comment]
Closed by #25
