### ISSUE TITLE
Bee class parameter validation

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#244]
Referring to previous conversations, BeeJS has to handle somewhere the parameter correctness checking to provide well formed information what kind of problem happened exactly during the process.
I think this checking could happen in Bee class level, leave for the exported modules do only the business logic part of the action.

**Comment by agazso** [comment]
Isn't this a duplicate of #202?

**Comment by AuHau** [comment]
Yeah I wanted to point out same thing as @agazso

**Comment by nugaon** [comment]
you are right guys, I thought it was just in a discussion. let's continue in #202
