### ISSUE TITLE
Typings are not verified for tests

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#257]
I believe that typings are not checked for our tests. I think this mainly comes from the fact that Jest uses webpack for the compilation of the TS files and webpack does not do any verifications as `tsc` does.

We could create another check inside our GitHub workflow that would check this. Or other suggestions are welcomed.

**Comment by nugaon** [comment]
As far as I know Jest use Babel for compiling typescript files and type defs are also checked in test folder as well by eslint when we run `npm run lint:check`.
Why do you think it is not verified, was there a misbehaviour?

**Comment by AuHau** [comment]
No, `npm run lint:check` does not check typings, nor Babel compilation. The only thing that does verification of types safety is `tsc` execution which is run as part of `npm compile:types` which only covers the source code.

When I was working on the splitting of tests PR, I noticed that some of my earlier refactors did not actually propagate to the tests files, because back then I relied on the pipeline to verify this, which turns out does not do it.

An example see https://github.com/ethersphere/bee-js/pull/258/files#diff-0fd67e80c291e1c63cd4ba4888ed29de9d3842e12bae155ba54dedfacf4609a4L5 here the `Topic` type is imported from an old place where it is not present anymore and I was able to merge that refactor without nothing detect this problem...

**Comment by vojtechsimetka** [comment]
I also noticed this a while back but I thought it's a bug in my editor/setup.

**Comment by nugaon** [comment]
I see, then we should introduce command `check:types` that runs `tsc` checking command on both src and test folders, am I right?

**Comment by AuHau** [comment]
Yeah agree with the `check:types`. I mean then we don't have to use the `compile:types` in the GitHub Workflow.
