### ISSUE TITLE
Revisit integration testing setup

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#270]
This morning @Cafe137 asked me for a help with integration tests as they were failing with `ECONNREFUSED`.

I am not sure how the integration testing setup was created. Currently the local bee nodes are by default searched at `http://bee-0.localhost`. I assume this is thanks to [`bee-local`](https://github.com/ethersphere/bee-local)? But at the same time we have the `./test/bee.sh` script that orchestrates the cluster with docker and is presented as the way to go to run the test but the nodes are not found under this URL which makes the test fails. It is possible to configure that with env. variable, but I think this should work out-of-the-box. 

So I would either change the defaults from `http://bee-0.localhost` to `http://localhost:1633` or fix the `./test/bee.sh` script to be reachable under that address.

@nugaon @agazso what do you think?

**Comment by vojtechsimetka** [comment]
I vote for changing the defaults.

**Comment by AuHau** [comment]
Yeah, we discussed it internally and we gonna change the defaults to support the `./test/bee.sh` and have custom setting for CI.
