### ISSUE TITLE
Run only one testfile

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#284]
Before PR #258 I could run test against only one particular testfile, but with the current setup it is not possible.

### Desired behaviour
`npm run test:node -- test/{some-test-file}` -> run only this passed file

### Actual behaviour
it runs all the tests

**Comment by AuHau** [comment]
Hmm I am not sure why it should not work, but I am not using this feature. For specification of concrete tests I use the [`-t`](https://jestjs.io/docs/cli#--testnamepatternregex) flag, which should work so in the meanwhile you can use that.

**Comment by nugaon** [comment]
I checked and for files there is an option to pass the desired test filename with `--testPathPattern`
