### ISSUE TITLE
Make a CI job for running compile tasks

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#29]
Currently the CI jobs do not run the webpack compile tasks. Therefore I found that the browser compile task is broken at the moment.

It would be good if the webpack compile task would run on every PR.

**Comment by nugaon** [comment]
in [.github/workflows/check.yaml](https://github.com/ethersphere/bee-js/blob/master/.github/workflows/check.yaml) you can see we currently compile our code with webpack, and the latest test related commit from PR #51 also requires to run browser side webpack compilation before run browser test.
Is it still relevant?
