### ISSUE TITLE
Expose postage stamps MAXIMUM_DEPTH and MINIMUM_DEPTH constatns

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#332]
As a UI developer I would love to know these limits at the time of developing the dapp so that I can inform user if they put in value out of the boundaries.

Ideally as a typescript developer, the input type would be limited to these boundaries (currently 16-255).

**Comment by AuHau** [comment]
I don't think it is possible to do range input type verification in TypeScript, but exposing the constants makes sense :-)

**Comment by vojtechsimetka** [comment]
Thanks! 

And yeah I know range verification is not really a thing and existing solutions (e.g. solution 2 in the [3rd commend here](https://stackoverflow.com/questions/39494689/is-it-possible-to-restrict-number-to-a-certain-range) ) would mean that user pro ably has to typecast any variable input. So forget about that part :)
