### ISSUE TITLE
Use only `bigint` for big amount numbers

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#335]
Using `number | bigint` is a bad practice IMHO as when using `number` it might "randomly" (from user perspective) starts to throw errors once the safe limit is exceeded, which might or might not be checked by the developer that uses this library. Enforcing using `bigint` will decrease bit of DX, but I think would be more error-prone. What do you think? 
@vojtechsimetka

**Comment by vojtechsimetka** [comment]
I always wanted to just use `bigint` but was overruled as the tooling and working with `bigint` is still not great. But from my point of view the benefits outweigh the downsides and I'd remove the `number` completely and use `bigint`.

Just BTW this discussion and resulting change should propagate even further. For example postage stamps right now have `depth` as `number` (and it can only be integer 16 - 255) but `amount` as `bigint`. I'd advocate to go all in.

**Comment by nugaon** [comment]
I'm also on the side to give back either `number` or `bigint` but never both, because otherwise you always should put a condition before its usage.

On other hand, I would not use `bigint` on those places where it is not necessary, because of that @vojtechsimetka mentioned, it is not convenient to work with. I think the mixed number like parameters (so one of them is `number`, the other is `bigint`) at one function is totally fine.

**Comment by AuHau** [comment]
> I always wanted to just use bigint but was overruled as the tooling and working with bigint is still not great. But from my point of view the benefits outweigh the downsides and I'd remove the number completely and use bigint.

Just BTW this discussion and resulting change should propagate even further. For example postage stamps right now have depth as number (and it can only be integer 16 - 255) but amount as bigint. I'd advocate to go all in.

I see. Hmmmm. Somehow I am bit reluctant to go "all in" and would only use `bigint` if we have to. But I admit that then it might be bit confusing for the devs on when to use `bigint` and when normal numbers. That said, I think there can be straightforward guideline that when you are dealing with token amounts then you should use `bigint`s and otherwise numbers... So I think it is not such a big deal.

>I'm also on the side to give back either number or bigint but never both, because otherwise you always should put a condition before its usage.

On other hand, I would not use bigint on those places where it is not necessary, because of that @vojtechsimetka mentioned, it is not convenient to work with. I think the mixed number like parameters (so one of them is number, the other is bigint) at one function is totally fine.

Sorry, should have specified that this issue is related to "input types". We are never returning type with both options.
