### ISSUE TITLE
Require `options.size` when uploading file with `Readable`

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee-js#353]
As observed in `swarm-cli`:

To upload a single file using the `uploadFile` function, we tried two things:

- Reading the data to memory with `readFileSync` and then passing that to upload
- Creating a `Readable` with `createReadStream` and then passing that to upload

After uploading, we query the `tag` to get the `total` amount of chunks, as well as the `processed` and `synced` status.

When using `readFileSync`, the `total` amount of chunks is correct. With `createReadStream`, it is always `2` or `3`, even when we expect thousands. 

---

To understand this `HTTP` / `axios` behaviour, I created a sandbox project with one server and two clients.

The server simply prints the incoming chunk sizes:

```
import { createServer } from 'http'

createServer((req, res) => {
    req.on('data', chunk => {
        console.log(chunk.toString().length)
    })
    req.on('end', () => {
        res.end('ok')
    })
}).listen(3333)
```

Then I create a ~15MB binary file to `POST`:

```
dd if=/dev/urandom count=1500 bs=10000 > data.bin
```

And `POST` it using `readFileSync`:

```
import axios from 'axios'
import { readFileSync } from 'fs'

axios.post('http://localhost:3333', readFileSync('data.bin'), { maxContentLength: Infinity, maxBodyLength: Infinity })
```

The chunk sizes look very similar:

```
62027
62034
62045
61993
62191
62218
62184
61996
62177
```

Now with `createReadStream`:

```
import axios from 'axios'
import { createReadStream } from 'fs'

axios.post('http://localhost:3333', createReadStream('data.bin'), { maxContentLength: Infinity, maxBodyLength: Infinity })
```

The chunk sizes vary:

```
62018
203
61822
212
61825
218
61769
225
61955
237
61972
251
```

The assumption is that with streaming, a different `Transfer-Encoding` is used, probably `chunked`, which Bee does not handle correctly.

My other theory is that the `Content-Length` header is missing or is wrong, and Bee uses that to determine total amount of chunks.

**Comment by Cafe137** [comment]
Related: https://github.com/ethersphere/bee/issues/1224

**Comment by Cafe137** [comment]
Headers for `readFileSync`:

```
{
  accept: 'application/json, text/plain, */*',
  'content-type': 'application/x-www-form-urlencoded',
  'user-agent': 'axios/0.21.1',
  'content-length': '15000000',
  host: 'localhost:3333',
  connection: 'close'
}
```

Headers for `createReadStream`: 

```
{
  accept: 'application/json, text/plain, */*',
  'content-type': 'application/x-www-form-urlencoded',
  'user-agent': 'axios/0.21.1',
  host: 'localhost:3333',
  connection: 'close',
  'transfer-encoding': 'chunked'
}
```

**Comment by AuHau** [comment]
The problem was in not specifying size of the file. We should have check for this in place.
