### ISSUE TITLE
"Over-exposed" utility functions

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#385]
Looking on what is exposed as part of the `Utils` namespace, I think there is a lot of parts that are purely internal and I am not sure why user should have access to it. Especially as it extends the public API that is then tightened to SemVer.

```ts
export * as Collections from './collection' // <- should expose only the helpers the @Cafe137 created
export * as Bytes from './bytes' // <- also not sure if it is needed
export * as Data from './data' // <- I would definitely remove this one
export * as File from './file' // <- This will be removed in the directory streaming PR
export * as Hex from './hex' // <- I guess this one makes sense
export * as Tar from './tar' // <- I would definitely remove this one
export * as Eth from './eth' // <- This one makes sense
export * as Hooks from './hooks' // <- This one could be only deprecated with the Fetch PR, but if we gonna have breaking release we might remove it as well.
export * as Pss from './pss'
export { setDefaultHeaders } from './safe-axios'
export { keccak256Hash } from './hash'
```

**Comment by agazso** [comment]
Maybe I would go as far as not having `export *` because it can have unintended consequences. For example an internal utility function exposed publicly, then after an internal refactor landing in a different file would break the public API.

@r0qs is there anything in the above list that would negatively affect you?

**Comment by r0qs** [comment]
Hi, thanks for considering my use case. I indeed use those functions, mostly the `eth`, `hex` and `bytes` modules.
But after our discussion around the issue https://github.com/ethersphere/bee-js/issues/379 I decided to do my own wrapper around the bee api to have more control over the feeds and pss functionalities.
So this change will not affect me anymore:)
