### ISSUE TITLE
reuploadPinnedData fails with 404

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee-js#393]
reuploadPinnedData contains the following TODO:

```
    try {
      // TODO: This should be detected by Bee, but until https://github.com/ethersphere/bee/issues/1803 is resolved
      //  it is good idea to do some input validation on our side.
      await this.getPin(reference)
    } catch (e) {
      if (e.status === 404) {
        throw new BeeArgumentError('The passed reference is not locally pinned!', reference)
      }
    }
```

While PATCH /bzz/{reference} does expect the data to be pinned, the /pins API has been modified to only return the top-most reference pins.  This eliminates the usefulness of reuploadPinnedData to force a reupload of only a smaller portion of a colleciton by reference since reuploadPinnedData requires a pin of the specified reference to exist.  This forces the user to trigger a reupload of an entire collection (1.25GB in my case) even when a much smaller portion is known to need repair.

**Comment by AuHau** [comment]
Hmm, that is a very interesting point worth definitely investigating. 

I guess we should then ask the Bee team to implement correct validation as it is only for them possible to do the correct validation as they have internally the data for it. I will try to urge them to do this.

**Comment by AuHau** [comment]
@ldeffenb do you think that with the way how the reupload is implemented in Bee, it would work for non-root hashes as well?

**Comment by ldeffenb** [comment]
> @ldeffenb do you think that with the way how the reupload is implemented in Bee, it would work for non-root hashes as well?

Yes, I have in fact used it that way to force a reupload of a submanifest chunk as well as a data/value chunk.  I just wish there was a way to tell it to ONLY do the specified chunk and not chase the forks out of a manifest block recursively as it does now.
