### ISSUE TITLE
Review browser tests

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#42]
With the current configuration is possible to test in headless Chromium browser, but the don't utilize it in our Jest tests.

We should [review our browser tests according to that](https://github.com/ethersphere/bee-js/pull/41#pullrequestreview-550863568).

**Comment by agazso** [comment]
It seems that there is a problem with Typescript definitions when running browser tests. For example I created a test that is using the browser File API (that is defined in `lib.dom.d.ts` provided by Typescript) but when running the tests this gives a `ReferenceError: File is not defined` error message.

See:
https://github.com/ethersphere/bee-js/pull/47
