### ISSUE TITLE
Throw error if an entry is too long for the tar archive format used by Bee

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee-js#421]
Swarm-CLI: https://github.com/ethersphere/swarm-cli/issues/250
Bee: https://github.com/ethersphere/bee/issues/2542

1. Figure out what tar format Bee is using
2. Check in bee-js if the data to be uploaded contains any invalid entries for that specific tar spec
3. Throw human friendly error

**Comment by AuHau** [comment]
Well, honestly I would like to remove usage of Tar for directory upload as you can see in the #416 

Unfortunately, it is currently blocked as Bee does not allow nested directory upload using multipart upload as you can see https://github.com/ethersphere/bee-js/pull/416

**Comment by bee-worker** [comment]
Release [v8.3.0](https://github.com/ethersphere/bee-js/releases/tag/v8.3.0) addresses this.
