### ISSUE TITLE
[v2.0.0][Node.js][stream] `uploadFile` stalls with 8MB file, uploading enclosing directory with `uploadFilesFromDirectory` succeeds

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee-js#422]
I have not debugged it much yet, but I encountered this issue in swarm-cli.

I have an 8MB binary file for testing purposes. When I try to upload it, the `bee.uploadFile` never settles.

When I upload the directory containing the 8MB binary file as well as some other smaller files, the operation succeeds (`bee.uploadFilesFromDirectory`).

```
curl -X POST http://localhost:1633/bzz?name=8mb.bin -H "accept: application/json, text/plain, */*" -H "content-length: 8000000" -H "content-type: application/octet-stream" -H "swarm-postage-batch-id: 6f4622d44519709f66ae1e6c52f2000c232e30cb867713a983660e49c85a5552" -H "user-agent: bee-js/2.0.0"
```

**Comment by Cafe137** [comment]
I am uploading to an Ubuntu 20.04 VPS with Bee-Factory running 1.1 with one queen and one worker.

**Comment by Cafe137** [comment]
Also there are no logs in Bee indicating that anything is happening at all

**Comment by AuHau** [comment]
Well, did it really errored out? Or what is exactly the problem? Types?

`ky` is typed for the WHATWG `ReadableStream` but on NodeJS it uses `node-fetch` which support `Readable` (and hence `ReadStream` which is extended from `Readable`).
