### ISSUE TITLE
Module import naming style

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#46]
Currently our module imports look like this: `import * as name from './modules/name'

There was a comment from @nugaon saying that we could use module names starting with uppercase:
https://github.com/ethersphere/bee-js/pull/45#discussion_r543112432

However that would introduce naming collisions because we also have types called `Tag`, `Collection` etc.

One solution could be to use names like `TagModule`, `FileModule` etc.

**Comment by AuHau** [comment]
I think since then this was not revisited and I don't see us moving in this direction, so I am closing this. Feel free to reopen if you think we should bring it on table again.
