### ISSUE TITLE
Add request and response objects to BeeResponseError

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#462]
I am working with a Node.js based command-line tool that uses bee-js and when there is a problem, the only information I can get from the `BeeResponseError` object is the error message and the HTTP status code. However sometimes it is not enough information to see what went wrong, especially when working with a Bee node where I have no access to the error logs.

It would be good if the `BeeResponseError` would also include information about the request and the response that was made, so that there is more context when debugging an issue.

**Comment by AuHau** [comment]
Hmmm I understand your pain, but not sure what would help you here. The only thing I have come up with is exposing the request and response objects, but in the same time I am not sure if it good idea, if they are not some hidden downsides.

**Comment by agazso** [comment]
Well, what would have helped me previously is to include at least the `url` and the `method` of the request and the actual response value, even if it is not JSON (this may be related to #456).

I was also thinking of adding the `Request` and `Response` objects to the `BeeResponseError` as properties and I agree that there may be downsides. I could potentially think of this (but that does not mean there may not be others):
- If the HTTP library is changed to not use the Fetch API then this may be a breaking change in the public API. I am not sure this is a huge risk though, because in that case many other things may change as well so a breaking change may be inevitable.

As an alternative I was thinking of tracking the HTTP calls completely on the application level with the `onRequest` and `onResponse` hooks so that when an error happens I have the information stored. However this can get cumbersome easily if there are overlapping requests.
