### ISSUE TITLE
Provide sane defaults for gateway URL and postage stamp id

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#567]
Most developer who try out the library will want to test their code as soon as possible without having to bother with installing components and setting them up.

The idea is that we could provide sane defaults for the api URL with `https://api.gateway.ethswarm.org` and the default postage stamp id `0000000000000000000000000000000000000000000000000000000000000000` as exported constants.

**Comment by bee-worker** [comment]
Release [v8.3.0](https://github.com/ethersphere/bee-js/releases/tag/v8.3.0) addresses this.
