### ISSUE TITLE
Bee-js cannot be executed in service worker script

### ISSUE THREAD

**Issue by tomicvladan** [ethersphere/bee-js#586]
When the library is loaded in a service worker script, the following error occurs:

`Uncaught ReferenceError: document is not defined`

The reason is that the library includes the `blob-polyfill` which tries to access the document object.

**Note:**
One temporary solution is to replace that polyfill with an empty object, in webpack config:

```javascript
plugins: [
  new NormalModuleReplacementPlugin(
      /blob-polyfill/,
      path.join(srcDir, 'polyfills', 'Blob.js')
    ),
]
```

src/polyfills/Blob.js
```javascript
module.export = {};
```

**Comment by bee-worker** [comment]
Release [@ethersphere/bee-js v3.3.4](https://github.com/ethersphere/bee-js/releases/tag/v3.3.4) addresses this.
