### ISSUE TITLE
Add configuration options to Bee class constructor

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#59]
When setting up the `Bee` class the constructor only requires a url to be passed. This is not always enough, for example we are using a convention for calculating the Debug API port address from the passed url but since this is user configurable in Bee this may be not always correct.

One idea to address this is that the constructor would accept a second optional argument of object type where all the optional features could be configured.

**Comment by AuHau** [comment]
I think this is already present with in `Bee` class for default signer and I don't see any more usecases that we could bring into it, so for now I am closing this.
