### ISSUE TITLE
Bee-JS Upload and Download batch is too small

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee-js#595]
https://bee-js.ethswarm.org/docs/upload-download/ shows an example with:

```
const postageBatchId = await bee.createPostageBatch("100", 17)
```

This is way too small of an amount to survive long enough in the mainnet for testing.  I just did an extensive support with a person following this example and it took us nearly two hours to work our way around to the fact that the stamp had expired and therefore his uploads were not getting into the swarm.

**Comment by agazso** [comment]
I opened an issue in the documentation repo which is the source of this information.

https://github.com/ethersphere/bee-js-docs/issues/134

Therefore I would close the issue here.
