### ISSUE TITLE
Update the NodeInfo interface with missing attributes

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-js#608]
The `NodeInfo` interface currently has shape (see [bee-js docs](https://bee-js.ethswarm.org/docs/api/interfaces/NodeInfo)):
```ts
{
   beeMode: BeeModes
   gatewayMode: boolean
}
```

But the bee 1.5.0 returns:
```ts
{
  "beeMode": "light",
  "gatewayMode": false,
  "chequebookEnabled": true,
  "swapEnabled": true
}
```
This is a great opportunity to introduce #606 for this endpoint

**Comment by bee-worker** [comment]
Release [@ethersphere/bee-js v3.3.4](https://github.com/ethersphere/bee-js/releases/tag/v3.3.4) addresses this.
