### ISSUE TITLE
Support Swarm CID references 

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#648]
Swarm has already CID [library](https://github.com/ethersphere/swarm-cid-js/) and also CID based linking `{cid}.bzz.link`.
Would be awesome, if bee-js also supported this kind of reference.

**Comment by vojtechsimetka** [comment]
Thanks for the issue. This is actually a topic of our internal discussion today, in general we would love to add such support :).

**Comment by AuHau** [comment]
We will implement solution where:

 - we will accept CIDs and decode them using the `swarm-cid-js` library
 - we will extend the `UploadResult` interface into `CIDUploadResult` that will be returned on upload methods for which we have CID support (manifests, and feeds)

**Comment by bee-worker** [comment]
Release [v4.1.0](https://github.com/ethersphere/bee-js/releases/tag/v4.1.0) addresses this.
