### ISSUE TITLE
Support for waiting on postage stamp to be usable

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#650]
It would be good to have a way for the user to easily wait until a new postage stamp is usable. I can see few ways:

 1. Add an option to `createPostageStamp()` method that would block the Promise until the stamp is usable and only then returning the stamp ID
 2. Utility function

**Comment by vojtechsimetka** [comment]
I think both options make sense and probably don't exclude each other. I would however be more interested in 1. and make such behavior default.

**Comment by vojtechsimetka** [comment]
Here is a referenco to how we implemented it in gateway-proxy https://github.com/ethersphere/gateway-proxy/blob/master/src/stamps.ts#L64-L88 including tests https://github.com/ethersphere/gateway-proxy/blob/master/test/stamps.spec.ts#L244-L272

**Comment by AuHau** [comment]
Agree, but I would refrein from making it default as that would be breaking change. But I agree that it should be default behaviour but I would wait until breaking release for making the switch (which should be soon anyhow).

**Comment by bee-worker** [comment]
Release [v4.1.0](https://github.com/ethersphere/bee-js/releases/tag/v4.1.0) addresses this.
