### ISSUE TITLE
Invalid regular expression error in Safari 

### ISSUE THREAD

**Issue by mattiaz9** [ethersphere/bee-js#686]
Updating from version 3.3.4 to 4.0.0 will cause the following Error in Safari: `Invalid regular expression: invalid group specifier name `. 
This problem is only present in Safari, it works fine in Chrome.

It's probably related to this: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by AuHau** [comment]
Ou 😳  Thanks for the issue report! Will fix it asap.

**Comment by bee-worker** [comment]
Release [v4.1.0](https://github.com/ethersphere/bee-js/releases/tag/v4.1.0) addresses this.
