### ISSUE TITLE
Support HEAD request on `bytes` EP

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#727]
With Bee [1.6.2](https://github.com/ethersphere/bee/releases/tag/v1.6.2) it is possible to get the content length of a swarm reference by sending HEAD request to the `bytes` endpoint.
BeeJS could have a method in the `Bee` class that utilizes this feature.

**Comment by bee-worker** [comment]
Release [v8.2.0](https://github.com/ethersphere/bee-js/releases/tag/v8.2.0) addresses this.
