### ISSUE TITLE
`ky` update is required

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#762]
[ky](https://www.npmjs.com/package/ky) just recently published its new version where they fixed the ["The duplex member must be specified for a request with a streaming body"](https://github.com/sindresorhus/ky/issues/450) with which we also encountered.

all [streaming request](https://developer.chrome.com/articles/fetch-streaming-requests/#streaming-request-bodies) are currently affected at the moment in Chrome.

**Comment by AuHau** [comment]
Btw. Bee-js does not yet uses streaming requests so I'm not sure how it is relevant?

**Comment by molekilla** [comment]
Fairdrive create account feature is currently broken in Chrome browser. Unless there is a workaround, shim or polyfill, we'd need a  fix or upgrade

**Comment by AuHau** [comment]
Can you please expand on what and how are you using and what does not work? Preferably having reproduction example?

**Comment by molekilla** [comment]
![image_2022-09-08_19-15-22](https://user-images.githubusercontent.com/1248071/189342805-9fe56524-41bb-4a0e-ac48-daadffdae4fd.png)

**Comment by agazso** [comment]
@molekilla can you link to the project to a file where this call originates?

It's hard to find the problem if you don't give enough information. I tried to look at the [Fairdrive app](https://github.com/fairDataSociety/fairdrive-theapp) but it does not even seem to have bee-js as dependency.

**Comment by molekilla** [comment]
This https://github.com/fairDataSociety/fdp-storage/blob/c4c08822efd8293e1cbda086d720b3c96551be8b/src/account/account-data.ts#L170

**Comment by nugaon** [comment]
simple testpage to test out the problem: https://github.com/nugaon/bee-js-issue-762

**Comment by molekilla** [comment]
@agazso @nugaon @AuHau https://github.com/sindresorhus/ky/commit/0b141f1725442039a439b683d32d42e9b9d52559

**Comment by tfius** [comment]
just update to latest ky-universal version of 0.10.1 (current version is 0.8.2 and is 2 years old) 
https://github.com/sindresorhus/ky-universal/releases

**Comment by AuHau** [comment]
We have a pre-release out that is ESM-only package and has updated Ky: [`6.0.0-pre.0`](https://www.npmjs.com/package/@ethersphere/bee-js/v/6.0.0-pre.0). Can you please try it out and see if that solves your problem?

Btw. after updating puppeteer to latest version which uses the latest Chrome I saw the same problem, and after updating Ky all good.

**Comment by bee-worker** [comment]
Release [v5.1.2](https://github.com/ethersphere/bee-js/releases/tag/v5.1.2) addresses this.
