### ISSUE TITLE
Remove `skipLibCheck` when possible

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee-js#771]
Currently, there are several typing errors in our dependencies that block having full type check of our dependencies, so had to enable the `skipLibCheck`. Some of the issues:

 - [ ] https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/issues/241

**Comment by bee-worker** [comment]
Release [v8.3.0](https://github.com/ethersphere/bee-js/releases/tag/v8.3.0) addresses this.
