### ISSUE TITLE
support `/envelope` endpoint

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#930]
recently new feature has been added to the Bee that created new endpoint `/envelope` POST which generates a Postage Stamp for the requested chunk address with the node's Postage Batch.

This should be supported by BeeJS.

Feature PR: https://github.com/ethersphere/bee/pull/4723

**Comment by bee-worker** [comment]
Release [v8.2.0](https://github.com/ethersphere/bee-js/releases/tag/v8.2.0) addresses this.
