### ISSUE TITLE
support pre-signed postage stamps on chunk operations

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#937]
SOC, feed and chunk related operations awaits for postage batch ID.

One should be able to provide postage stamp serialization instead postage batch ID.

This feature is [supported in Bee](https://github.com/ethersphere/bee/pull/4719) by setting `Swarm-Postage-Stamp` header with hex encoded stamp serialization instead of `Swarm-Postage-Batch-Id` in request.

**Comment by bee-worker** [comment]
Release [v8.2.0](https://github.com/ethersphere/bee-js/releases/tag/v8.2.0) addresses this.
